services:
  vault-node1:
    image: hashicorp/vault
    container_name: vault-node1
    command: server
    ports:
      - "8200:8200"
      - "8201:8201"
    environment:
      VAULT_LOCAL_CONFIG: |
        ui = true

        listener "tcp" {
          address       = "0.0.0.0:8200"
          tls_cert_file = "/vault/certs/vault.crt"
          tls_key_file  = "/vault/certs/vault.key"
        }

        storage "raft" {
          path    = "/vault/data"
          node_id = "node1"
        }

        disable_mlock = true
        api_addr      = "https://127.0.0.1:8200"
        cluster_addr  = "https://127.0.0.1:8201"
    volumes:
      - ./vault-node1/data:/vault/data
      - ./certs:/vault/certs
    cap_add:
      - IPC_LOCK
    restart: unless-stopped
